<a href="https://colab.research.google.com/github/ohse-emily/pytorch/blob/master/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
print('GPU')
!nvidia-smi

GPU
Mon Sep 26 06:56:15 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+---

TEXT

In [53]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


In [54]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [55]:
scalar.ndim

0

In [56]:
scalar.item()

7

In [57]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [58]:
vector.ndim # [] 괄호의 수 = 차원

1

In [59]:
vector.shape # elements 의 수

torch.Size([2])

In [60]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [61]:
MATRIX.ndim

2

In [62]:
MATRIX[0]

tensor([7, 8])

In [63]:
MATRIX.shape

torch.Size([2, 2])

In [64]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [4,2,1]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [4, 2, 1]]])

In [65]:
TENSOR.ndim

3

In [66]:
TENSOR.shape #[[3,3,3]]

torch.Size([1, 3, 3])

In [67]:
# random tensors 
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4222, 0.1777, 0.5091, 0.4743],
        [0.1866, 0.1628, 0.2103, 0.8752],
        [0.1113, 0.8222, 0.6336, 0.3154]])

In [68]:
random_image_size_tensor = torch.rand(size=(224,224,3))

In [69]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [70]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [71]:
ones.dtype

torch.float32

In [72]:
zeros.dtype

torch.float32

In [73]:
torch.range(0,10)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  """Entry point for launching an IPython kernel.


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [74]:
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
one_to = torch.arange(start=1, end=1000, step=50)
one_to
# one_to.ndim

tensor([  1,  51, 101, 151, 201, 251, 301, 351, 401, 451, 501, 551, 601, 651,
        701, 751, 801, 851, 901, 951])

In [76]:
one_to_ten = torch.arange(start=1, end=11, step=1)
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [77]:
# tenser dataTypes - dtype다르면 에러 (shage, device도! )
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what dataType is the tensor 
                               device=None, # what device is your tensor on
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [78]:
float_32_tensor.dtype

torch.float32

In [79]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [80]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [81]:
int_32_tensor = torch.tensor([3,6,9]
                             ,dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [82]:
int_32_tensor.dtype

torch.int64

In [83]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [84]:
float_32_tensor.device

device(type='cpu')

In [85]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5424, 0.1644, 0.4176, 0.4417],
        [0.5562, 0.6266, 0.6106, 0.7886],
        [0.4733, 0.7468, 0.7570, 0.9250]])

In [86]:
print(some_tensor)
print(f"DataType of tensor:, {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}") # tensor.size() = tensor.shape 
print(f"Device of tensor : {some_tensor.device}")

tensor([[0.5424, 0.1644, 0.4176, 0.4417],
        [0.5562, 0.6266, 0.6106, 0.7886],
        [0.4733, 0.7468, 0.7570, 0.9250]])
DataType of tensor:, torch.float32
Shape of tensor : torch.Size([3, 4])
Device of tensor : cpu


In [87]:
tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [88]:
tensor * 10

tensor([10, 20, 30])

In [89]:
tensor

tensor([1, 2, 3])

In [90]:
tensor - 10

tensor([-9, -8, -7])

In [91]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [92]:
# Matrix Multiplication

# 1. Element-wise multiplication
# 2. Matrix multiplication (= dot product)

tensor

tensor([1, 2, 3])

In [93]:
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [94]:
#Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [95]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 314 µs, sys: 50 µs, total: 364 µs
Wall time: 372 µs


In [96]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 46 µs, sys: 0 ns, total: 46 µs
Wall time: 49.8 µs


tensor(14)

In [97]:
# matmul == @ 
tensor @ tensor

tensor(14)

In [98]:
torch.matmul(torch.rand(3,2), torch.rand(2,1))

tensor([[0.7918],
        [0.6246],
        [0.3259]])

In [99]:
# tensor_A = torch.tensor([[1,2],
#                         [4,5],
#                         [6,7]])

# tensor_B = torch.tensor([[7,10],
#                         [8,11],
#                         [9,12]])
# # mm == torch.matmul
# torch.mm(tensor_A, tensor_B)

In [100]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]), torch.Size([3, 2]))

In [101]:
# transpose : switches the axes or dimensions of a given tensor 
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]), torch.Size([2, 3]))

In [102]:
# 
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B={tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must maut")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")
torch.mm(tensor_A, tensor_B.T)

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B=torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must maut
Output:

tensor([[ 27,  30,  33],
        [ 78,  87,  96],
        [112, 125, 138]])

Output shape: torch.Size([3, 3])


tensor([[ 27,  30,  33],
        [ 78,  87,  96],
        [112, 125, 138]])

In [103]:
tensor_A.T

tensor([[1, 4, 6],
        [2, 5, 7]])

In [104]:
### Tensor Aggregation  - the min, max, mean, sum, etc.

In [105]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [106]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [107]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [108]:
x.dtype # int64 == long ## mean은 float32 dtype이 필요하다.

torch.int64

In [109]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [110]:
torch.rand(2,3)

tensor([[0.4374, 0.8019, 0.8300],
        [0.8297, 0.2059, 0.4228]])

In [111]:
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [112]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [113]:
# index를 return 한다. 
x.argmax()

tensor(9)

In [114]:
x[9]

tensor(91)

In [115]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

# reshaping / stacking / squeezing / unsqueezing tensors

reshaping - input tensor 를 reshape하는 것 

View - 특정shape의 Input tensor의 view를 반환하지만 원래 tensor와 같은 메모리에 저장한다. 

stacking - 여러개의 tensors들을 옆으로 또는 위로 결합한다.

squeeze - 1개의 차원을 tensor로부터 제거

unsqueeze - 1개의 차원을 Tensor에 더하기

Permute - 특정방법으로 변경된 차원과 Input의 view를 Return 


In [116]:
x = torch.arange(1.,10.)
x[0].dtype, x, x.shape

(torch.float32, tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [117]:
#Reshape - add an extra dimension : 기존의 size와 호환될 수 있어야함. 
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [118]:
a = torch.arange(4.)
a
torch.reshape(a, (2,2))

tensor([[0., 1.],
        [2., 3.]])

In [119]:
# Change the view
z = x.view(1,9)  # z, x는 같은 메모리다. 
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [120]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [121]:
# Stack tensors on top 
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [122]:
# Squeeze & Unsqueeze 
y = torch.zeros(2,1,2,1,2)
# y = torch.squeeze(y).size()
y

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [123]:
torch.squeeze(y, 1).size()

torch.Size([2, 2, 1, 2])

In [124]:
e = torch.ones(2,4,1,3,1)
e.squeeze(dim=4).size()

torch.Size([2, 4, 1, 3])

In [125]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [126]:
x_reshaped.shape

torch.Size([1, 9])

In [127]:
x_squeezed = x_reshaped.squeeze()

In [128]:
# Unsqueeze() : adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add an extra dimension with unsqueeze 
x_unsqueezed = x_squeezed.unsqueeze(0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape : {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape : torch.Size([1, 9])


In [129]:
# torch.permute - rearranges the dimensions of a target tensor in a spcified order 
# "permute" : 참조하는 memory가 같다.
x_original = torch.rand(size=(224,224,3)) # [heigth, width, colour_channels] 이미지

# dim order 변경하기 
x_permuted = x_original.permute(2,0,1)
x_permuted.size()

print(f"Previous shape : {x_original.shape}")
print(f"New shape : {x_permuted.shape}")

Previous shape : torch.Size([224, 224, 3])
New shape : torch.Size([3, 224, 224])


In [130]:
x_original[0,0,0] = 123
x_original[0,0,0], x_permuted[0,0,0]

(tensor(123.), tensor(123.))

In [131]:
## Indexing (Selecting data from tensors)

x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [132]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [133]:
x[0][0] # == x[0,0]

tensor([1, 2, 3])

In [134]:
x[0][0][0]

tensor(1)

In [135]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [136]:
# get all values of 0th and 1st dimensions but only index 1 of 2nd dimension 
x[:, :, 1]

tensor([[2, 5, 8]])

In [137]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [138]:
x[0, :, 1]

tensor([2, 5, 8])

In [139]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:] # == x[0,0]

tensor([1, 2, 3])

In [140]:
# Index on x to return 9
x, x[0][2][2], x[0,2,2], x[:, :, 1]


# Index on x to return 3,6,9

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), tensor(9), tensor(9), tensor([[2, 5, 8]]))

In [141]:
# Pytorch tensors & Numpy 
# Numpy data ----> pytorch tensor  : torch.from_numpy(ndarray)
# pytorch tensor -----> Numpy data   : torch.Tensor.numpy()

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [142]:
array.dtype # numpy 의 default datatype = float64

dtype('float64')

In [143]:
torch.arange(1., 8.).dtype  # tensor의 default dataType은 float32 

torch.float32

In [144]:
tensor.dtype

torch.float64

In [145]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [146]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [147]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [148]:
# Reproducibility 재생력/복사가능성 (trying to take random out of random)

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9496, 0.8794, 0.4740, 0.3092],
        [0.4806, 0.9160, 0.4500, 0.7290],
        [0.9008, 0.4230, 0.1474, 0.3447]])
tensor([[0.0727, 0.1202, 0.1128, 0.1176],
        [0.4258, 0.9963, 0.1363, 0.0721],
        [0.4498, 0.5739, 0.2215, 0.6415]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [149]:
# random but reproducible tensors 만들기

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)  # 한번 더 해줘야함. 한번 사용하면 사라지는 것으로 (?) 생각 
random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Running tensors and pytorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + pyTorch working behind the scenes to make everything good. 
 
 1. Easiest - use Google colab for a free GPU (options to upgrade as well)

 2. Use your own GPU - takes a little bit of setup and requires the investments of purchasing a GPU.

 3. Use cloud computing - GCP, AWS, Azure, 
 

In [150]:
!nvidia-smi

Mon Sep 26 06:56:16 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [155]:
torch.cuda.is_available()

True

In [156]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [158]:
# torch.cuda.device_count()

SyntaxError: ignored

In [160]:
# Putting tensors (and models) on the GPU (because it's faster)
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [162]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [166]:
## numpy 는 오직 cpu에서만 works : move tensors back to the CPU 

# if tensor is on GPU, can't transform it to numpy 
tensor_on_gpu.numpy()

TypeError: ignored

In [168]:
# to fix the GPU tensor with Numpy issue, we can first set it to the CPU 

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [169]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [197]:
## EXERCISES
RANDOM_SEED = 0

torch.cuda.manual_seed_all(1234)

torch.manual_seed(RANDOM_SEED)
tensor = torch.rand(7,7)
torch.manual_seed(RANDOM_SEED)
tensor2 = torch.rand(1,7)
multiplied = torch.mm(tensor, tensor2.T)
# multiplied

torch.manual_seed(1234)
t1 = torch.rand(2,3)
torch.manual_seed(1234)
t2 = torch.rand(2,3)
device = "cuda" if torch.cuda.is_available() else "cpu"
t1 = t1.to(device)
t2 = t2.to(device)
answer = torch.mm(t1, t2.T)
minn = answer.min()
maxx = answer.max()
min_index = answer[0]
max_index = answer[len(answer)-1]
minn, maxx, min_index, max_index

torch.manual_seed(7)
newTensor = torch.rand([1,1,1,10])
last = newTensor.squeeze()
last[0], last[1], last.shape


(tensor(0.5349), tensor(0.1988), torch.Size([10]))