<a href="https://colab.research.google.com/github/ohse-emily/pytorch/blob/master/data_loading_and_customizing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 0. PyTorch Basic 공부
1. 변수 설정 / 매서드 등
2. 미분 적용 방식 
 
강의 제공 : Youtube 딥러닝호형 DL bro https://www.youtube.com/watch?v=8PnxJ3s3Cwo&list=PLHOsBEAyYj3xf4i20sCA5o8MgVW5sIiHD&index=11


In [2]:

import torch
import numpy as np

x = torch.empty(5,4)
x


tensor([[2.1438e-35, 0.0000e+00, 1.5695e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.2140e-36, 0.0000e+00],
        [3.5733e-43, 0.0000e+00, 1.5975e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.2140e-36, 0.0000e+00],
        [3.5733e-43, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [3]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [4]:
torch.zeros(2)

tensor([0., 0.])

In [5]:
torch.rand(4,5)

tensor([[0.6796, 0.4268, 0.8156, 0.7516, 0.9019],
        [0.9303, 0.2283, 0.7056, 0.7003, 0.4698],
        [0.6922, 0.6752, 0.1840, 0.7064, 0.5619],
        [0.6968, 0.8358, 0.2431, 0.4629, 0.6817]])

In [6]:
# list / array 주어졌을 때 
l = [13,4]
r = np.array([4, 56,7])

torch.tensor(l)

tensor([13,  4])

In [7]:
torch.tensor(r)

tensor([ 4, 56,  7])

In [8]:
x.size()

torch.Size([5, 4])

In [9]:
type(x)

torch.Tensor

In [10]:
x = torch.rand(3,3)
y = torch.rand(3,3)
print(x)
print(y)

tensor([[0.5904, 0.5841, 0.4642],
        [0.8409, 0.4581, 0.0756],
        [0.0185, 0.3180, 0.7976]])
tensor([[0.6861, 0.3023, 0.3102],
        [0.8824, 0.1407, 0.8997],
        [0.1143, 0.2348, 0.5949]])


In [11]:
x+y

tensor([[1.2765, 0.8865, 0.7744],
        [1.7233, 0.5988, 0.9754],
        [0.1328, 0.5528, 1.3926]])

In [12]:
y.add_(x)
# print(y)

tensor([[1.2765, 0.8865, 0.7744],
        [1.7233, 0.5988, 0.9754],
        [0.1328, 0.5528, 1.3926]])

In [13]:
y

tensor([[1.2765, 0.8865, 0.7744],
        [1.7233, 0.5988, 0.9754],
        [0.1328, 0.5528, 1.3926]])

In [14]:
x

tensor([[0.5904, 0.5841, 0.4642],
        [0.8409, 0.4581, 0.0756],
        [0.0185, 0.3180, 0.7976]])

In [15]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.6098, 0.2049],
        [0.1882, 0.9318]])
tensor([[0.2119, 0.5261],
        [0.5811, 0.1685]])


In [16]:
y.multiply_(x)

tensor([[0.1292, 0.1078],
        [0.1094, 0.1570]])

In [17]:
y

tensor([[0.1292, 0.1078],
        [0.1094, 0.1570]])

In [18]:
y[1,1]

tensor(0.1570)

In [19]:
y[:,1]

tensor([0.1078, 0.1570])

In [20]:
x = torch.rand(8,8)
print(x)

tensor([[0.8650, 0.9800, 0.0260, 0.2318, 0.2687, 0.0196, 0.0512, 0.3455],
        [0.1545, 0.9787, 0.6197, 0.7647, 0.7575, 0.4673, 0.1733, 0.4769],
        [0.0920, 0.6025, 0.4145, 0.6258, 0.8933, 0.8654, 0.8301, 0.7347],
        [0.1357, 0.1004, 0.6896, 0.6587, 0.9205, 0.1610, 0.2690, 0.0046],
        [0.6030, 0.1282, 0.4735, 0.1999, 0.2974, 0.2014, 0.8812, 0.5028],
        [0.2832, 0.5203, 0.9889, 0.3456, 0.9801, 0.9435, 0.5927, 0.9903],
        [0.9550, 0.7679, 0.9260, 0.7704, 0.6281, 0.4578, 0.0714, 0.7923],
        [0.4901, 0.8965, 0.8450, 0.7561, 0.6528, 0.0727, 0.3579, 0.1525]])


In [21]:
x.view(2,32)

tensor([[0.8650, 0.9800, 0.0260, 0.2318, 0.2687, 0.0196, 0.0512, 0.3455, 0.1545,
         0.9787, 0.6197, 0.7647, 0.7575, 0.4673, 0.1733, 0.4769, 0.0920, 0.6025,
         0.4145, 0.6258, 0.8933, 0.8654, 0.8301, 0.7347, 0.1357, 0.1004, 0.6896,
         0.6587, 0.9205, 0.1610, 0.2690, 0.0046],
        [0.6030, 0.1282, 0.4735, 0.1999, 0.2974, 0.2014, 0.8812, 0.5028, 0.2832,
         0.5203, 0.9889, 0.3456, 0.9801, 0.9435, 0.5927, 0.9903, 0.9550, 0.7679,
         0.9260, 0.7704, 0.6281, 0.4578, 0.0714, 0.7923, 0.4901, 0.8965, 0.8450,
         0.7561, 0.6528, 0.0727, 0.3579, 0.1525]])

In [22]:
# -1을 넣으면 자동 계산해줌 
x.view(-1, 16)

tensor([[0.8650, 0.9800, 0.0260, 0.2318, 0.2687, 0.0196, 0.0512, 0.3455, 0.1545,
         0.9787, 0.6197, 0.7647, 0.7575, 0.4673, 0.1733, 0.4769],
        [0.0920, 0.6025, 0.4145, 0.6258, 0.8933, 0.8654, 0.8301, 0.7347, 0.1357,
         0.1004, 0.6896, 0.6587, 0.9205, 0.1610, 0.2690, 0.0046],
        [0.6030, 0.1282, 0.4735, 0.1999, 0.2974, 0.2014, 0.8812, 0.5028, 0.2832,
         0.5203, 0.9889, 0.3456, 0.9801, 0.9435, 0.5927, 0.9903],
        [0.9550, 0.7679, 0.9260, 0.7704, 0.6281, 0.4578, 0.0714, 0.7923, 0.4901,
         0.8965, 0.8450, 0.7561, 0.6528, 0.0727, 0.3579, 0.1525]])

In [23]:
y = x.numpy()
y

array([[0.86504143, 0.9799733 , 0.02596784, 0.23184437, 0.2686811 ,
        0.01956606, 0.05122912, 0.34550995],
       [0.1545459 , 0.9786902 , 0.61967736, 0.76468456, 0.75753176,
        0.46728873, 0.17326325, 0.47687268],
       [0.09202623, 0.6025456 , 0.41453886, 0.62577903, 0.8933469 ,
        0.86535114, 0.830069  , 0.73472494],
       [0.13570154, 0.10039753, 0.68957984, 0.6586712 , 0.92052263,
        0.16099209, 0.2689988 , 0.00456911],
       [0.60300136, 0.12819797, 0.47354084, 0.19992399, 0.29735053,
        0.20136398, 0.8812313 , 0.50280845],
       [0.28324354, 0.520315  , 0.9888866 , 0.34559846, 0.9801272 ,
        0.943486  , 0.59271216, 0.9903411 ],
       [0.9550202 , 0.7678522 , 0.925994  , 0.7703883 , 0.6280544 ,
        0.45781714, 0.07143486, 0.79233545],
       [0.49009526, 0.89649165, 0.845005  , 0.7560849 , 0.6528197 ,
        0.07270503, 0.35793626, 0.15254402]], dtype=float32)

In [24]:
type(y)

numpy.ndarray

In [25]:
# item은 tensor가 scalar일 때만 사용 가능 
x = torch.ones(1)
x

tensor([1.])

In [26]:
# loss Fn 값 sacalar값으로 나옴 
x.item()

1.0

In [27]:
#미분 - 딥러닝에서 필수 loss Fn
# 1. 변수 선언 (+데이터 입력)
x = torch.ones(2,2, requires_grad=True) # requires_grad default = False /   x대해 미분을 할 수 있도록 x에 관한 연산을 모두 추적할 수 있도록 함 
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [28]:
# 2. 모델 내 연산 예측값 산출
y = x +1
print(y)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [29]:
# 3. 손실함수 계산
z = 2*y**2
print(z)

# 4. 손실 산출
res = z.mean() # 평균 
res

tensor([[8., 8.],
        [8., 8.]], grad_fn=<MulBackward0>)


tensor(8., grad_fn=<MeanBackward0>)

In [30]:
print(res)

tensor(8., grad_fn=<MeanBackward0>)


In [31]:
# d(res)/dx_i = x+i + 1
# res = (z_1 + .. + z_4)4
# z_i = 2 y_i ** 2
# z_i = 2(x_i+1)**2
res.backward() # res 기준으로 연쇄법칙을 적용하겠다

In [32]:
# x에 대한 미분값 보기
print(x.grad)

tensor([[2., 2.],
        [2., 2.]])


In [33]:
# 재정리 : 딥러닝 구조와 똑같은 흐름 
# 최적화라는 것은 손실함수를 기준으로 해서 각 변수마다 미분을 하게 되는 것 ---> res를 기준으로 미분을 하게 되는 것 
import torch

x = torch.ones(2,2, requires_grad=True) # x라는 변수를 잡고 변수에 대해 추적을 하게끔 만듬 / 텐서를 계산하면서 
y = x+1 # y값을 산출하게 되고 
z = 2*y**2 # y값은 loss Fn에 이용이 되고 
res = z.mean() # loss값을 산출하게 됨 ---- 마지막에 나온 이 scalar값으로 미분을 하게 되는데 미분을 할 때 requires_grad가 == True인 변수에 대해 미분을 함 
res.backward() # res 기준으로 연쇄법칙을 적용하겠다

print(x.grad) # x 미분값을 보기 

tensor([[2., 2.],
        [2., 2.]])


# 1. PyTorch 데이터 불러오기 
 1. pytorch 가 제공하는 데이터 
 2. 같은 클래스 별 폴더 이미지 데이터 이용
 3. 개인 데이터 사용 (2 types) 

In [34]:
import torch
import torchvision 
import torchvision.transforms as tr # 데이터를 불러온 후 바로 전처리 가능하게 만드는 라이브러리
from torch.utils.data import DataLoader, Dataset # DataLoader = 배치 사이즈 형태로 만들어서 실제로 학습할 때 이용할 수 있는 형태를 만들어 주는 라이브러리 / Dataset : 튜닝할 때 사용
import numpy as np

## 1) Pytorch 제공 데이터 사용하기

In [35]:
transf = tr.Compose([tr.Resize(8), tr.ToTensor()]) # 전처리를 할 때, Compose 안에 있는 순서대로 수행하게 됨 
# transforms on PIL Images -> numpy or list 같은 타입은 오류가 남 * PIL 이미지여야 한다. 


In [36]:
trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transf) # transform=transf : 들어오는 데이터에 전처리를 해주겟다~ 
testset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=transf)

  0%|          | 0/170498071 [00:00<?, ?it/s]

Extracting ./data/cifar-10-python.tar.gz to ./data
Files already downloaded and verified


In [37]:
trainset[0][0].size() # trainset[0] = tuple

torch.Size([3, 8, 8])

In [38]:
# batch 형태로 만들기 
trainloader = DataLoader(trainset, batch_size=50, shuffle=True, num_workers=2) # num_workers : 데이터를 로드할 때 써 프로세스(?)를 몇 개 쓰느냐 - 2,4 혹은 에러가 나면 0으로 놓기 
testloader = DataLoader(testset, batch_size=50, shuffle=True, num_workers=2)

# 여기까지 데이터 불러오기 / 전처리까지 완료 

In [39]:
# 가져온 데이터의 수를 배치사이즈 50으로 나누면 배치의 수가 나옴
len(trainset), len(testset), len(trainloader), len(testloader) 

(50000, 10000, 1000, 200)

In [ ]:
# trainloader 안 실제 값을 보는 방법
dataiter = iter(trainloader)
# list(dataiter)
images, labels = dataiter.next()
images
# [50,3,8,8]
# 50: 배치 사이즈 
# 3: 채널 수
# 8: 이미지 너비
# 8: 이미지 높이 

## 2) 같은 클래스 별 폴더 이미지 데이터 이용


In [41]:
!ls

data  drive  sample_data


In [42]:
cd drive

/content/drive


In [43]:
cd MyDrive/pytorch

/content/drive/MyDrive/pytorch


In [44]:
# 폴더 안에 클래스 별로 나누기 
# ./class/tiger ./class/lion  -> 이렇게 나뉘어져 있으면 ImageFolder()를 사용할 수 있음
transf = tr.Compose([tr.Resize(16), tr.ToTensor()])
trainset = torchvision.datasets.ImageFolder(root='./class', transform=transf) # ImageFolder() 는 ./class 안에 있는 폴더 별로 labeling을 다르게 매겨서 서치해줌 + 바로 전처리 사용 가능 
trainloader = DataLoader(trainset, batch_size=10, shuffle=False, num_workers=2)
print(len(trainloader))

6


In [45]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [46]:
trainset[0][0].size()

torch.Size([3, 16, 16])

In [ ]:
list(trainloader)

## 3) 개인 데이터 사용 (2 types) 


In [75]:
# import preprocessing 

train_images = np.random.randint(256, size=(20,32,32,3)) # numpy 형태로 들어왔다고 가정 : 32 by 32짜리 이미지 3 채널짜리가 20개 있음 
train_labels = np.random.randint(2, size=(20,1)) # 그에 따른 label 20개가 있다고 가정

# preprocessing ..
# train_images, train_labels = preprocessing(train_images, train_labels)  <- preprocessing()에서 전처리가 다 되고 넘어온다. 

print(train_images.shape, train_labels.shape)  # (20,32,32,3) 20: 배치사이즈, 32by32 : 이미지 사이즈, 3 : 채널 사이즈 

(20, 32, 32, 3) (20, 1)


class 내부에서 데이터 불러와 전처리 등등 할 수 있는데 왜 외부에서 데이터 들어오는 방식으로 했는지 ? 

=> ImageFolder는 클래스 별로 폴더 나눠놓으면 세 줄이면 끝나는데 (구글 드라이브에서 가져온 거) 이 방식으로 가능하지 않은 경우가 있기 때문
1. 다른 작업과 공용으로 쓰이는 데이터인 경우
2. 폴더가 아닌 SQL같은 곳에서 넘어오는 경우


In [76]:
# dataset class를 상속받을 클래스 만들기 


class TensorData(Dataset):
  def __init__(self, x_data, y_data): # 외부에서 데이터 들어올려고 x_data, y_data 작성함
    self.x_data = torch.FloatTensor(x_data) # tensor로 변경 근데 이제 타입이 float 인..     // Tensor로 바꾸기 전 전처리가 이미 다 되어 있음 위의 preprocessing()에서 
    self.x_data = self.x_data.permute(0,3,1,2) ## permute()함수로 이미지 개수, 채널 수, 이미지 너비, 높이로 순서 바꾸기 
    self.y_data = torch.LongTensor(y_data) # tensor로 변경 근데 이제 타입이 Long인..
    self.len = self.y_data.shape[0] # 데이터의 개수 

  def __getitem__(self, index):
    return self.x_data[index], self.y_data[index] # tuple형태로 내보낼 것

  def __len__(self):
    return self.len


In [77]:
train_data = TensorData(train_images, train_labels) # class instance 생성, 데이터 두 개(x_data, y_data) 불러오니까 두 개 넣어줌
train_loader = DataLoader(train_data, batch_size=10, shuffle=True)

In [78]:
train_data[0][0].size()

torch.Size([3, 32, 32])

In [79]:
dataiter = iter(train_loader)
images, labels = dataiter.next()

In [80]:
images.size()

torch.Size([10, 3, 32, 32])

개인 데이터에 이제 transfor= 을 사용해보기 

In [81]:
##### 기본 양식 
# from torch.utils.data import Dataset

# class MyDataset(Dataset):

  # def __init__(self):

  # def __getitem__(self, index):
              
  # def __len__(self):

In [82]:
from torch.utils.data import Dataset

class MyDataset(Dataset):
  def __init__(self, x_data, y_data, transform=None):
    self.x_data = x_data
    self.y_data = y_data
    self.transform = transform
    self.len = len(y_data)
              
  def __getitem__(self, index):
    sample = self.x_data[index], self.y_data[index] # tuple 형태를

    if self.transform:  # 내보내기 전 전처리 작업을 하겠다. 
      sample = self.transform(sample)

    return sample # transform=None이면 x_data, y_data 를 Tensor로 변환안했기 때문에 Numpy로 내보내짐 

  def __len__(self):
    return self.len

# transform을 수기로 class로 작성해보기
class ToTensor:
  def __call__(self, sample):
    inputs, labels = sample
    inputs = torch.FloatTensor(inputs)
    inputs = inputs.permute(2,0,1)
    return inputs, torch.LongTensor(labels)

class LinearTensor:
  def __init__(self, slope=1, bias=0):
    self.slope = slope
    self.bias = bias

  def __call__(self, sample):
    inputs, labels = sample
    inputs = self.slope*inputs + self.bias
    return inputs, labels 

In [83]:
trans = tr.Compose([ToTensor(), LinearTensor(2,5)]) # !!! tr.toTensor()를 사용하지 못하는 이유 : tr은 PIL images 형태여야함 - 지금 가지고 있는 데이터가 Numpy - 타입이 다르기 때문에 에러남 
ds1 = MyDataset(train_images, train_labels, transform=trans)
train_loader1 = DataLoader(ds1, batch_size=10, shuffle=True) # DataLoader로 배치형태로 변환
ds1[0][0].size()

torch.Size([3, 32, 32])

In [84]:
first_data = ds1[0]
features, labels = first_data
print(type(features), type(labels))

<class 'torch.Tensor'> <class 'torch.Tensor'>


In [85]:
dataiter1 = iter(train_loader1)
images1, labels1 = dataiter1.next()

In [ ]:
images1

In [87]:
class MyDataset(Dataset):
  def __init__(self, x_data, y_data, transform=None):
    self.x_data = x_data
    self.y_data = y_data
    self.transform = transform
    self.len = len(y_data)

  def __getitem__(self, index):
    sample = self.x_data[index], self.y_data[index]

    if self.transform:
      sample = self.transform(sample)

    return sample

  def __len__(self):
    return self.len

class MyTransform:
  def __call__(self, sample):
    inputs, labels = sample
    inputs = torch.FloatTensor(inputs)
    inputs = inputs.permute(2,0,1)
    labels = torch.FloatTensor(labels)

    transf = tr.Compose([tr.ToPILImage(), tr.Resize(128), tr.ToTensor(), tr.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])
    final_output = transf(inputs)

    return final_output, labels


In [88]:
ds2 = MyDataset(train_images, train_labels, transform=MyTransform())
train_loader2 = DataLoader(ds2, batch_size=10, shuffle=True)
# batch 하는 이유 : 학습 때 전체 학습하면 너무 느려져서 배치로 나누어 학습하기 위해

In [89]:
first_data = ds2[0]
features, labels = first_data
print(type(features), type(labels))

<class 'torch.Tensor'> <class 'torch.Tensor'>


In [90]:
features.size()

torch.Size([3, 128, 128])

In [ ]:
dataiter2 = iter(train_loader2)
images2, labels2 = dataiter2.next()
images2

# 2. 인공신경망 구축 : 기본 모델 구축 및 저장하기
이미지 중심의 모델

In [67]:
import torch
import torchvision
import torchvision.transforms as transforms # 데이터 불러온 후 전처리하기 위함 
from torch.utils.data import DataLoader # 배치 형태로 만들어주는 라이브러리

In [74]:
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,0.5,0.5), (0.5,0.5,0.5))])

trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=8, shuffle=True, num_workers=2)

testset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=8, shuffle=False, num_workers=2)

classes = ('plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

# CIFAR10 : 10개의 classes가 들어있는 이미지 파일임, 위의 classes 분류 10개의 파일

  0%|          | 0/170498071 [00:00<?, ?it/s]

Extracting ./data/cifar-10-python.tar.gz to ./data
Files already downloaded and verified


In [92]:
from google.colab import files
uploaded = files.upload()

Saving restaurants_names.csv to restaurants_names.csv


In [ ]:
uploaded

In [93]:
import pandas as pd
df = pd.read_csv('restaurants_names.csv')
